#!/usr/bin/env bash
# Rebuild integrations/hermes/agency-agents-router from the curated roster.
# Run this after adding, removing, or refreshing any file in .claude/agents/.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
for f in "$here"/.claude/agents/*.md; do
  b="$(basename "$f")"
  case "$b" in
    project-management-*) d=project-management ;;
    paid-media-*)         d=paid-media ;;
    *)                    d="${b%%-*}" ;;
  esac
  mkdir -p "$stage/$d" && cp "$f" "$stage/$d/$b"
done
python3 - "$here/divisions.json" "$stage" <<'PY'
import json, os, sys
src = json.load(open(sys.argv[1])); stage = sys.argv[2]
present = sorted(d for d in os.listdir(stage) if os.path.isdir(os.path.join(stage, d)))
missing = [d for d in present if d not in src["divisions"]]
if missing:
    sys.exit(f"divisions.json lacks an entry for: {missing}")
json.dump({"_note": src["_note"], "divisions": {k: src["divisions"][k] for k in present}},
          open(os.path.join(stage, "divisions.json"), "w"), indent=2)
PY
count="$(python3 "$here/scripts/build-hermes-plugin.py" --repo-root "$stage" --out "$here/integrations/hermes")"
# The generator writes a README that references upstream's convert.sh; ours is rebuilt here.
python3 - "$here/integrations/hermes/README.md" <<'PY'
import sys
p = sys.argv[1]; t = open(p).read()
t = t.replace("Generated by `scripts/convert.sh --tool hermes`.",
              "Generated by `scripts/build-hermes.sh` from the curated roster in `.claude/agents/`.")
t = t.replace("```bash\n./scripts/convert.sh --tool hermes\n./scripts/install.sh --tool hermes\n```",
              "```bash\n./scripts/standby.sh          # installs this plugin and the Claude Code agents\n./scripts/standby.sh hermes   # plugin only\n```")
t = t.replace("regenerate and reinstall the plugin from the latest Agency Agents\ncheckout",
              "run `./scripts/build-hermes.sh` and `./scripts/standby.sh hermes` again")
open(p, "w").write(t)
PY
echo "Hermes router plugin rebuilt with $count agents -> integrations/hermes/agency-agents-router"
